server:
  port: '@server.port@'

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        default_schema: ps
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari.maximum-pool-size: 10
  flyway:
    schemas: ps
    url: @db.url@
    table: flyway_schema_history

hibernate:
  physical_naming_strategy: com.rbkmoney.partyshop.entity.naming.SnakeCaseNamingStrategy

info:
  version: '@project.version@'
  stage: dev

kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: PartyShop
  ssl:
      enabled: false
      trust-store-location: "test"
      trust-store-password: "test"
      key-store-location: "test"
      key-store-password: "test"
      key-password: "test"
      key-store-type: PKCS12
      trust-store-type: PKCS12
  consumer:
      group-id: "PartyShop"
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 20
      max-poll-interval-ms: 30000
      session-timeout-ms: 30000
      party-management-concurrency: 7
  topics.party-shop.id: mg-events-party